chore: fix codecoverage (#159)
Fixing this error cause by updating to actions/upload-artifact@v4 and
actions/download-artifact@v4
```
Run actions/upload-artifact@v4
With the provided path, there will be [1](https://github.com/chanzuckerberg/cellxgene-ontology-guide/actions/runs/8455804882/job/23164145371#step:7:1) file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```